<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <RootNamespace>ScrcpyDex.WinUI</RootNamespace>
    <AssemblyName>ScrcpyDeX</AssemblyName>
    <SupportedOSPlatformVersion>10.0.18362.0</SupportedOSPlatformVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>ScrcpyDex.Program</StartupObject>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="src\App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <Page Remove="src\App.xaml" />
    <Resource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="WPF-UI" Version="3.0.5" />
  </ItemGroup>

</Project>
