package com.scrcpydex.server;

import android.os.Handler;
import android.os.Looper;

import com.scrcpydex.server.wrappers.DisplayManager;

import java.io.IOException;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Main Entry Point for ScrcpyDeX Server.
 * 
 * Executed via app_process in Android shell context (UID 2000).
 * Orchestrates the full lifecycle:
 * 1. Initializes Workarounds and Android event Looper
 * 2. Validates Samsung hardware compatibility
 * 3. Activates native Samsung DeX engine via Miracast loopback
 * 4. Monitors DeX display appearance via DisplayManagerGlobal
 * 5. Opens TCP port 27183 and awaits client/ffplay connection
 * 6. Streams continuous H.264 video generated by MediaCodec
 */
public final class Server {
    private static final int VIDEO_PORT = 27183;
    private static final AtomicBoolean running = new AtomicBoolean(true);

    private static DisplayManager displayManager;
    private static DexActivator dexActivator;
    private static VideoCapture videoCapture;
    private static ControlChannel controlChannel;
    private static ServerSocket videoServerSocket;

    public static void main(String[] args) {
        Ln.i("=================================================");
        Ln.i("      ScrcpyDeX Server v1.0 (Stage 1)            ");
        Ln.i("   Samsung DeX for PC via USB / Zero Wi-Fi Latency");
        Ln.i("=================================================");

        // 1. Prepare thread Looper for Handler and Callback support
        if (Looper.myLooper() == null) {
            Looper.prepare();
        }
        Handler mainHandler = new Handler(Looper.myLooper());

        // 2. Apply workarounds for app_process on Android 11+
        Workarounds.apply();

        displayManager = new DisplayManager();

        // 3. Support manual fast disconnect command
        if (args.length > 0 && "disconnect".equalsIgnoreCase(args[0])) {
            Ln.i("Disconnect command received. Terminating active DeX sessions...");
            displayManager.disconnectWifiDisplay();
            Ln.i("DeX sessions terminated successfully.");
            return;
        }

        // 4. Install ShutdownHook for automatic cleanup on USB disconnect or process termination
        Runtime.getRuntime().addShutdownHook(new Thread(Server::cleanup, "ScrcpyDeX-Cleanup"));

        try {
            // 5. Validate device compatibility
            CompatCheck.verify();

            // 6. Open ServerSocket on video port 27183 before activating DeX
            videoServerSocket = new ServerSocket(VIDEO_PORT, 1, InetAddress.getByName("127.0.0.1"));
            videoServerSocket.setReuseAddress(true);
            Ln.i("Video server listening on 127.0.0.1:" + VIDEO_PORT + " (waiting for client)...");

            // 7. Start Display event monitor
            DisplayWatch displayWatch = new DisplayWatch();
            displayWatch.startListening(mainHandler);

            // 8. Activate native DeX engine via loopback
            dexActivator = new DexActivator(displayManager);
            boolean activated = dexActivator.activate();
            if (!activated) {
                throw new RuntimeException("Failed to activate DeX session over RTSP loopback.");
            }

            // 9. Wait until the 'ScrcpyDeX' display is created in SurfaceFlinger
            Ln.i("Waiting for Samsung DeX display confirmation...");
            int displayId = displayWatch.waitForDisplay(15);
            if (displayId == -1) {
                throw new RuntimeException("Timeout: Samsung DeX display was not detected within 15 seconds.");
            }
            Ln.i(">>> Samsung DeX ready for streaming! ID=" + displayId + " <<<");
            System.out.println("DEX_ACTIVATED_DISPLAY_ID=" + displayId);

            // Activation-only mode (for direct use with scrcpy --display-id)
            if (args.length > 0 && "activate".equalsIgnoreCase(args[0])) {
                Ln.i("'activate' mode enabled. Keeping DeX session open until termination...");
                synchronized (Server.class) {
                    while (running.get()) {
                        try {
                            Server.class.wait();
                        } catch (InterruptedException ignored) {}
                    }
                }
                return;
            }

            // 10. Start control and input channel on port 27184
            controlChannel = new ControlChannel(
                displayId,
                displayWatch.getWidth(),
                displayWatch.getHeight(),
                displayWatch.getDpi(),
                Server::cleanup
            );
            controlChannel.start();

            // 11. Await video client connection (e.g. ffplay or C# client)
            Ln.i("Ready to accept connection on port " + VIDEO_PORT + "!");
            Socket clientSocket = videoServerSocket.accept();
            clientSocket.setTcpNoDelay(true);
            Ln.i("Client connected: " + clientSocket.getRemoteSocketAddress());

            // 12. Start H.264 capture and encoding
            videoCapture = new VideoCapture(
                displayId,
                displayWatch.getWidth(),
                displayWatch.getHeight(),
                clientSocket.getOutputStream()
            );
            videoCapture.start();

        } catch (IncompatibleDeviceException ide) {
            Ln.e("Incompatibility detected: " + ide.getMessage());
        } catch (Throwable t) {
            Ln.e("Fatal error in ScrcpyDeX server: " + t.getMessage(), t);
        } finally {
            cleanup();
        }
    }

    private static void cleanup() {
        if (!running.getAndSet(false)) {
            return;
        }
        Ln.i("Executing safe shutdown of ScrcpyDeX Server...");
        if (controlChannel != null) {
            controlChannel.stop();
        }
        if (videoCapture != null) {
            videoCapture.stop();
        }
        if (videoServerSocket != null && !videoServerSocket.isClosed()) {
            try {
                videoServerSocket.close();
            } catch (IOException ignored) {}
        }
        if (dexActivator != null) {
            dexActivator.stop();
        }
        if (displayManager != null) {
            displayManager.disconnectWifiDisplay();
        }
        Ln.i("Cleanup complete. Process terminated.");
    }
}
